27
liftedinit/ghostcloud-frontend pull request #46
Opened 2024-02-21 07:24 UTC by nblenke

## Description

- Create hook to check if there is a sessionId in localStorage
- Create login wrapper to check for sessionId, if present re-call handleLogin, but without redirect. This allows users to remain on another page on hard refresh
- Remove error that would appear if metas were not present on deployment component. This would appear briefly during hard refresh. A [toast error](https://github.com/liftedinit/ghostcloud-frontend/blob/main/lib/ghostcloud.ts#L317) will be presented if the query fails

## Related Issue

Fixes # 27

## Testing

## Breaking Changes (if applicable)

## Screenshots (if applicable)

## Checklist:

- [ ] I have read and followed the CONTRIBUTING guidelines for this project.
- [ ] I have added or updated tests and they pass.
- [ ] I have added or updated documentation and it is accurate.
- [ ] I have noted any breaking changes in this module or downstream modules.

2024-02-21 14:13 UTC, fmorency requested changes
Thanks! I tested in a fresh private window. Some comments

- The user is presented with the login prompt when visiting the root page for the first time. This is not expected behavior.
- After logging in using the prompt when visiting the root page for the first time, the user is not redirected to the dashboard.
- CI build is not passing, please fix.
- The loading spinner on the dashboard page is not centered.
![2024-02-21_09-09](https://github.com/liftedinit/ghostcloud-frontend/assets/1102868/28a39a32-15d2-4623-93ca-290c66b79f70)

2024-03-01 20:24 UTC, fmorency requested changes
Hey @nblenke, a few more comments.

- The user is still not redirected to the dashboard after logging in. 
- Pressing the `Get Started` button on the main page while being logged in does nothing.

2024-03-01 20:24 UTC, fmorency commented on __tests__/components/dashboard.test.tsx
> -  it("renders error if no data", () => {
Why did you remove this test?

2024-03-01 20:24 UTC, fmorency commented on components/login-wrapper.tsx
> +      handleLogin({}, false)
Why?

2024-03-01 20:24 UTC, fmorency commented on hooks/useAuthHandlers.ts
> +    console.log("==ev", ev)
Why?

2024-03-01 20:24 UTC, fmorency commented on pages/dashboard.tsx
> +  }, [isConnected, hasSession]) // eslint-disable-line
Add a comment on why you need this.

2024-03-01 22:17 UTC, nblenke commented on __tests__/components/dashboard.test.tsx
> -  it("renders error if no data", () => {
This was removed because the component was also removed.

2024-03-01 22:21 UTC, nblenke commented on components/login-wrapper.tsx
> +      handleLogin({}, false)
passing empty event here so we can still use `handleLogin` like so `onClick={handleLogin}`

2024-03-01 22:22 UTC, nblenke commented on hooks/useAuthHandlers.ts
> +    console.log("==ev", ev)
Added so we can still use handleLogin like so `onClick={handleLogin}`

2024-03-01 22:30 UTC, nblenke commented
> Hey @nblenke, a few more comments.
> 
> * The user is still not redirected to the dashboard after logging in.
This is on purpose. My thought was that if they were on the homepage/terms of service and refreshed, they would remain on the same page and not be redirected to the dashboard

> * Pressing the `Get Started` button on the main page while being logged in does nothing.
Fixed

2024-03-05 14:50 UTC, fmorency commented
> > Hey @nblenke, a few more comments.
> > 
> > * The user is still not redirected to the dashboard after logging in.
> 
> This is on purpose. My thought was that if they were on the homepage/terms of service and refreshed, they would remain on the same page and not be redirected to the dashboard

Is there any way to support both? I don't like that a first-time user is not redirected to the dashboard after logging in.

2024-03-05 22:46 UTC, nblenke commented
> Is there any way to support both? I don't like that a first-time user is not redirected to the dashboard after logging in.

I think I may have misunderstood. I've updated the "Login" menu item so that it will redirect to dashboard if clicked. I think this addresses the issue

2024-03-12 18:29 UTC, fmorency approved these changes

2024-03-12 18:30 UTC, merged